mybatis:
  type-aliases-package: com.itdreamworks.boilermanage.entity
spring:
  profiles:
    active: dev
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  resources:
    static-locations: classpath:static/,file:static/
cas:
  server-url-prefix: http://server.cas.com:8080/cas
  server-login-url: http://server.cas.com:8080/cas/login
  validation-type: cas
